baseURL = "https://natasha0301.github.io/Project-website/"
title = "Animal Wikipages"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Henrik Nielsen", "Inga Jensen", "Mikkel Andersen"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/peterampazzo/project-website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

